---
title: "Tidy Analysis of OSYM Data"
author: Oguz Ocal
date: April 20, 2018
output:
  html_document:
    toc: false
  pdf_document:
    toc: false
    toc_depth: 3
---

```{r,echo=FALSE,results="hide",message=FALSE}
library(knitr)
opts_chunk$set(tidy.opts=list(width.cutoff=60),tidy=TRUE)

```

This is an individual in-class exercise. At the end of the exercise, please upload html outputs to your Progress Journals. 

1. Get the highest `max_score` programs from each `exam_type`.

```{r}
library(tidyverse)

load("C:/Users/oguz.ocal/Desktop/OGZ/BOUN_ETM/Business Analytics/R/osym_data_2017_v2.RData")
head(osym_data_2017)


osym_data_2017 %>% group_by(exam_type) %>% summarise(maxscore = max(max_score))

```

2. Plot the top 10 programs of ÝSTANBUL ÜNÝVERSÝTESÝ in terms of total quota in a bar chart.


```{r}
osym_data_2017 <- osym_data_2017 %>% mutate(general_quota= as.numeric(general_quota), general_placement = as.numeric(general_placement))
top_10_iu<- osym_data_2017 %>% filter(university_name == "ÝSTANBUL ÜNÝVERSÝTESÝ") %>% arrange(desc(general_quota)) %>% slice(1:10)
top_10_iu

library(ggplot2)

ggplot(data=top_10_iu) + geom_bar(aes(x= reorder(program_name,-general_quota), y=general_quota), stat="identity") + theme(axis.text.x = element_text(angle=90))    

```



3. Calculate the fill rate (sum(`general_placement`)/sum(`general_quota`)) per city and return the top 10 cities.

```{r}
osym_data_2017 %>% group_by(city) %>% summarise(Fill_rate= sum(general_placement)/sum(general_quota)) %>% ungroup() %>% arrange(desc(Fill_rate)) %>% slice(1:10)
```
